name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java_version: [21]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java_version }}
        distribution: temurin
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.4
      if: matrix.os == 'windows-latest'
      with:
        minimum-size: 6GB
    - name: Build
      uses: gradle/gradle-build-action@v3.1.0
      with:
        arguments: check --scan
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
